name: Test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: macos-11
    name: Test
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          set -ex
          sudo xcode-select -s /Applications/Xcode_13.0.app

          xcodebuild test -scheme 'xcresulttool-example' \
            -destination "platform=iOS Simulator,name=iPhone 13 mini" \
            -resultBundlePath TestResults.xcresult \
            -enableCodeCoverage YES

      - uses: kishikawakatsumi/xcresulttool@coverage
        with:
          path: TestResults.xcresult
        if: always()
